# 사용할 OpenJDK 버전의 베이스 이미지 선택
FROM openjdk:17

# 작업 디렉토리 생성 및 설정
WORKDIR /app

# 필요한 파일 복사
COPY backend_dummy/gradle /app/gradle
COPY backend_dummy/gradlew /app/
COPY backend_dummy/build.gradle.kts /app/
COPY backend_dummy/settings.gradle.kts /app/
COPY backend_dummy/src /app/src

# 권한 부여 및 빌드 도구 실행
RUN chmod +x ./gradlew
RUN ./gradlew build -x test

# 빌드 결과물을 실행
ENTRYPOINT ["java","-jar","/app/build/libs/backend_dummy-0.0.1-SNAPSHOT.jar"]
