server:
  port: 7071

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/smudy
    username: ssafy
    password: ssafy
    driver-class-name: org.postgresql.Driver
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: k10d111.p.ssafy.io
      port: 9736
      password: dnrjsdkehfdkdhk

jwt:
  secret-key: VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2