server:
  port: 7071

spring:
  application:
    name: auth-service
  datasource:
    url: ENC(LOQ8dn9ei6+pX752IFd56v/dZi1VSH2nxeiAlgia3cptBT6YJ0zNRl1Dgwk6Ou6XWH7V9OlZKFSsbGBQ7aTrsg==)
    username: ENC(U1prS9CmmDnKNHS7OJdYtw==)
    password: ENC(G/jBy28DXfR039pmAt8RLn6V6vmQWVhJ)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ENC(Qp2Qjwju79uZqZoRRM+VVWJoz7lvyfawXt2a8DEQ2yU=)
      port: 9736
      password: ENC(3E9aOPuhala96rXjTVqHa721HtNVGGay)

jwt:
  secret-key: ENC(+ebEWdCqIhlFeh2InAoDO8eKE9YTAk9L9vTOk5p9unmreZG3u1P2Lya2PTS9jfEtTUx2rziDI/3UuesNgNJA0QFgb5uJV2XiIo1FRaDv/IGhWHPij+AgXUXkYebPwzT1vvu7ndrwzh4=)

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
