server:
    port: 7073

spring:
    application:
        name: study-service

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: ${BACK_URL}:8762/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 1
        lease-expiration-duration-in-seconds: 2
