server:
  port: 7073
openAI:
  key:
    ENC(xu6+KbV1SydVKv3/90LbAVe/rL72sXTScajRz+qQui1pqcbEq6+iKpfX5sAw6YgpatR0VJm13K1hJRhaKzQRwqvAD4tkBOO1)
spring:
  application:
    name: study-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ENC(rpbEWzTb6CXgLJ6X3DCOj5Qqfh384kFVEmpdC4ReEyq6Eg2HO5GawEYyUpipBVDqIP9JvxQQOxU37GjCBC73ag==)
    username: ENC(U1prS9CmmDnKNHS7OJdYtw==)
    password: ENC(G/jBy28DXfR039pmAt8RLn6V6vmQWVhJ)
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      host: ENC(yShAuKyz3zIKoVfc4ziqT6xVQSXXYuLmweQqS96xHfA=)
      port: ${MONGO_PORT}
      authentication-database: ENC(VU+PicUTWOuC/oDTeDQqng==)
      database: ENC(XXx2efl26LFLrUJKaKlCMA==)
      username: ENC(RCqgUnR3zVGKs7wAmzAmAw==)
      password: ENC(fnLscKJDfmi24jpS6um5dWC70TuDihWm)

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2