def gatewayimage

pipeline {
    agent any

    environment {
        APIGATEWAY_IMAGE_NAME = "${env.APIGATEWAY_IMAGE_NAME}"
        CONTAINER_NAME = 'Api_Gateway'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'echo "Starting Build Back Docker Image"'
                    dir('smudy_backend/backend/apigateway-service') {
                            withDockerRegistry(credentialsId: 'docker', url: 'https://registry.hub.docker.com') {
                                apigatewayImage = docker.build("${APIGATEWAY_IMAGE_NAME}:${env.BUILD_NUMBER}", ".")

                                // Docker 빌드 결과 출력
                                if (apigatewayImage != 0) {
                                    echo "Docker build succeeded: ${APIGATEWAY_IMAGE_NAME}:${env.BUILD_NUMBER}"
                                    docker.withRegistry('https://registry.hub.docker.com', 'docker') {
                                        apigatewayImage.push()
                                    }
                                } else {
                                    error "Docker build failed"
                                }
                        }
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'docker rm -f Api_Gateway || true'
                    sh "docker run -d --name ${CONTAINER_NAME} -p 8000:8000 ${APIGATEWAY_IMAGE_NAME}:${env.BUILD_NUMBER}"
                }
            }
        }
    }
}
