def gatewayimage

pipeline {
    agent any

    environment {
        // 도커 이미지 태그를 설정합니다. Git 커밋 ID를 사용할 수 있습니다.
        DOCKER_IMAGE = 'API_GATEWAY:${GIT_COMMIT}'
        // 도커 레지스트리 주소 설정
        DOCKER_REGISTRY = 'https://registry.hub.docker.com'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    dir('smudy_backend/backend/apigateway-service') {
                        // Docker 이미지를 빌드합니다.
                        gatewayImage = docker.build(env.DOCKER_IMAGE)
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    dir('smudy_backend/backend/apigateway-service') {
                        // Docker 레지스트리에 로그인 및 이미지 푸시
                        withDockerRegistry(credentialsId: 'docker', url: env.DOCKER_REGISTRY) {
                            if (gatewayImage != null) {
                                gatewayImage.push()
                            } else {
                                error "Docker build failed"
                            }
                        }
                    }
                }
            }
        }

        stage('Cleanup') {
            steps {
                dir('smudy_backend/backend/apigateway-service') {
                    sh 'docker rmi $DOCKER_IMAGE'
                }
            }
        }
    }

    post {
        always {
            // 항상 실행: 테스트 결과를 수집
            junit '**/build/test-results/test/*.xml'
            // 빌드 과정에서 생성된 아티팩트 정리
            cleanWs()
        }
    }
}
