spring:
    application:
        name: user-service
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true #To beautify or pretty print the SQL
          show_sql: true #show sql
          dialect: org.hibernate.dialect.PostgreSQLDialect

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: ENC(U1prS9CmmDnKNHS7OJdYtw==)
        password: ENC(G/jBy28DXfR039pmAt8RLn6V6vmQWVhJ)
        driver-class-name: org.postgresql.Driver

    data:
      mongodb:
        host: ENC(yShAuKyz3zIKoVfc4ziqT6xVQSXXYuLmweQqS96xHfA=)
        port: ${MONGO_PORT}
        authentication-database: ENC(VU+PicUTWOuC/oDTeDQqng==)
        database: ENC(XXx2efl26LFLrUJKaKlCMA==)
        username: ENC(RCqgUnR3zVGKs7wAmzAmAw==)
        password: ENC(fnLscKJDfmi24jpS6um5dWC70TuDihWm)

    ai:
      vectorstore:
        pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536

      openai:
        api-key: sk-proj-0rB49TSpPmvh6kpyAfOqT3BlbkFJY9xQabVcDik5sYK8xdlO
        base-url: https://api.openai.com
        embedding:
          options:
            model: text-embedding-3-small

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

jwt:
  secret: ENC(+ebEWdCqIhlFeh2InAoDO8eKE9YTAk9L9vTOk5p9unmreZG3u1P2Lya2PTS9jfEtTUx2rziDI/3UuesNgNJA0QFgb5uJV2XiIo1FRaDv/IGhWHPij+AgXUXkYebPwzT1vvu7ndrwzh4=)

logging:
  level:
    org:
      springframework:
        security: debug